file_save_path: "/content/drive/MyDrive/TempData/WikiRecs"
suffix: "2021_07_08"
outfile: "sampled_users_2021_07_08.csv" # CSV file to write the resulting user names and ids to
edit_histories_file_pattern: "edit_histories_2021_07_08_{}.feather" # Output for edit histories (needs a {} for where to place the number)

edit_lookback: 1000000 # How many edits to look back in Wikipedia history
users_per_chunk: 500 # How many users to pull before dumping to a file (for the sake of ram)

earliest_timestamp: "2021-01-01T01:00:00Z" # How far back to go (format e.g. 2021-02-11T05:35:34Z)